apiVersion: v1
kind: Service
metadata:
  name: learn-jenkins-app
  namespace: default
spec:
  selector:
    app: learn-jenkins-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
